In [10]:
##Question 1: Calculations

#Compute E1 in SI Units 

import numpy as np
hbar = 1.054571e-34
m = 9.109383e-31
L = 1e-9
pi = np.pi

E1 = pi**2 * hbar**2 / (2 * m * L**2)
print("E1 is", E1, "J")

##Full Answer provided on print out

E1 is 6.024658523923367e-20 J


In [9]:
### Question 2: Calculations

#Defining coordinate system
x = np.linspace(0,L,100)

V = -2 * (x-0.5e-9)**3 + 0.5e-9

L = 1e-9

def H_ij(i,j): 
    
    a = 2 * np.sin (j* np.pi)* np.sin (i * np.pi)
    b = (np.pi**2 * j**2) / 2 
    
    if i==j:
        ham_int = a + b

    else: 
        ham_int = a
        
    return ham_int 

H_mat = np.zeros((3,3))
for i in range(1,4):
    for j in range(1,4):
        H_mat[i-1][j-1] = H_ij(i, j)
print(H_mat)

c = np.zeros(3)
c[0] = 1
c[1] = 0
c[2] = 0
Hc = np.dot(H_mat,c)
E = np.dot(np.transpose(c),Hc)
E_opt, c_opt = np.linalg.eig(H_mat) 

print ("Ground state energy is", np.min(E_opt), "Joules" )




#print(E_opt[0]) 
#print(c_opt[0])
  

[[ 4.93480220e+00 -5.99903913e-32  8.99855870e-32]
 [-5.99903913e-32  1.97392088e+01 -1.79971174e-31]
 [ 8.99855870e-32 -1.79971174e-31  4.44132198e+01]]
Ground state energy is 4.934802200544679 Joules
